wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.8
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1666617560
    t:
      1:
      - 1
      - 5
      - 10
      - 11
      2:
      - 1
      - 5
      - 10
      - 11
      3:
      - 2
      4: 3.9.7
      5: 0.12.8
      6: 4.17.0
      8:
      - 1
      - 3
      - 5
